### PR TITLE
Droopescan

### PR DESCRIPTION
**Pull request by gkroon**
I hereby submit an ebuild for #184. Please note that `dev-python/cement` needs to be unmasked as `droopescan` depends on version >=2.6.

### CODE REVIEW

**Comment by gkroon** [comment]
I must admit I don't fully know how to. Should I add an entry in profiles/pentoo/base/package.accept_keywords/dev-python?

**Comment by blshkv** [comment]
Yeap, you can add it with full version

**Comment by gkroon** [comment]
Like this?

**Comment by blshkv** [comment]
Cool, perfect!

**Pull request merged**
