### PR TITLE
dependency-check-bin: cleanup + minor fixes

### PR DESCRIPTION
**Pull request by gkroon**
needs to be run as root in order to update the CVE database in /etc/dependency-check/data

### CODE REVIEW

**Comment by blshkv** [comment]
Please run repoman and fix tabs

**Comment by blshkv** [comment]
also, there is no point in -r1 since you just increase a version

**Comment by blshkv** [comment]
ok, nothing critical. Thanks!

**Comment by gkroon** [comment]
> btw, it is kind of wrong to update system data, that's why it was in bin. The tool need to keep a dabase somewhere in ~./tool by right.

I'm not sure, if more users are using the system, then they will also pull in another extra ~500 MB of CVE details in all their homedirs, right?

**Comment by blshkv** [comment]
Yeah, updates always tricky

**Pull request merged**
