### PR TITLE
update yara-rust bindings

### PR DESCRIPTION
**Pull request by necrose99**

### CODE REVIEW

**Comment by blshkv** [comment]
```
>>> Source unpacked in /var/tmp/portage/app-forensics/yara-rust-0.12.0/work
>>> Preparing source in /var/tmp/portage/app-forensics/yara-rust-0.12.0/work/yara-rust-0.12.0 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/app-forensics/yara-rust-0.12.0/work/yara-rust-0.12.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/app-forensics/yara-rust-0.12.0/work/yara-rust-0.12.0 ...
 * cargo build --release
error: could not find `Cargo.toml` in `/var/tmp/portage/app-forensics/yara-rust-0.12.0/work/yara-rust-0.12.0` or any parent directory
 * ERROR: app-forensics/yara-rust-0.12.0::pentoo failed (compile phase):
 *   cargo build failed
```

**Comment by necrose99** [comment]
[yara-rust-0.11.1.ebuild.txt](https://github.com/pentoo/pentoo-overlay/files/7542739/yara-rust-0.11.1.ebuild.txt)

[yara-rust-0.12.0.ebuild.txt](https://github.com/pentoo/pentoo-overlay/files/7542745/yara-rust-0.12.0.ebuild.txt)

hears a quick fresh run from cargo-ebuild  y

ara is the out file ....  rename to -rust.....ver$.ebuild
https://github.com/Hugal31/yara-rust/archive/refs/tags/v0.12.0.zip 
 _BREAKING CHANGES
The feature bundled-4_1_2 becomes bundled-4_1_3. However, since there are no ABI changes between the two versions, it is still compatible with yara v4.1.2._

dont know if the lib change is busting it .. 

https://github.com/Hugal31/yara-rust/archive/refs/tags/v0.11.1.zip 

both these do have the toml files inside  

cleaning up my installs both at present .. 



PS C:\Downloads\yara-rust-0.12.0\yara-rust-0.12.0>   (98% then the lack of yara.h ) so it should seem to work .. 


  --- stdout
  cargo:rustc-link-lib=dylib=yara

  --- stderr
  wrapper.h:1:10: fatal error: 'yara.h' file not found 
(scoop install yara or choco install yara)  or **[flare-vm](https://github.com/mandiant/flare-vm)**  (windows reverse/victim-box /IR incident response etc... )  ez fix ..

**Comment by blshkv** [comment]
yah, the problem that  cargo-ebuild just generates a template, you have to fix it later. 
But you keep submitting broken ebuilds and wasting my time

**Comment by necrose99** [comment]
yara-rust-0.11.1.ebuild.txt |  yara-src = "0.1.1" 1  yara = "0.11.1"  

yara-rust-0.12.0.ebuild.txt || yara-src = "0.1.2+3.11.0" yara = "0.12.0"   

 often cargo ebuild gives ebuilds that just work .. most of the time... 

**_other times it misses crates_** .. few features i wish they'd add ievendori'ng a raw crate ie src-uri/tarball  etc or add crates by lookup to ebuild... or other novice friendly .... but whom i kidding  or add sub crate ie ./lib-crate-sub

**Pull request closed without merging**
