### PR TITLE
net-wireless/gps-sdr-sim :: update after new commit

### PR DESCRIPTION
**Pull request by richardredditch**
commit 654a9888c54218766909e15fe8139e4bc8e83ecc

### CODE REVIEW

**Comment by richardredditch** [comment]
link: https://github.com/osqzss/gps-sdr-sim/commit/654a9888c54218766909e15fe8139e4bc8e83ecc

**Comment by ZeroChaos-** [comment]
Is this ready for merge?

**Comment by richardredditch** [comment]
I can confirm that with this change I can emerge without issues.

**Comment by richardredditch** [comment]
https://pastebin.com/JQ9ZVja2

**Comment by ZeroChaos-** [comment]
Thanks, lgtm

**Pull request merged**
