### PR TITLE
pwncat 0.1.1 (update: 0.1.0 -> 0.1.1)

### PR DESCRIPTION
**Pull request by cytopia**
# pwncat 0.1.1

Updating pwncat 0.1.0 to pwncat 0.1.1.

I've updated the Manifest as follows:
```bash
#!/usr/bin/env bash

VERSION="0.1.1"

BYTES="$( curl -sS --fail -L \
	"https://github.com/cytopia/pwncat/archive/v${VERSION}.tar.gz" --output - \
	| wc -c \
)"
BLAKE2B="$( curl -sS --fail -L \
	"https://github.com/cytopia/pwncat/archive/v${VERSION}.tar.gz" --output - \
	| python2 -c 'from pyblake2 import blake2b;import sys; print blake2b(sys.stdin.read()).hexdigest()' \
)"
SHA512="$( curl -sS --fail -L \
	"https://github.com/cytopia/pwncat/archive/v${VERSION}.tar.gz" --output - \
	| sha512sum \
	| awk '{print $1}' \
)"

cat <<- EOF
DIST pwncat-${VERSION}.tar.gz ${BYTES} BLAKE2B ${BLAKE2B} SHA512 ${SHA512}
EOF
```

Please let me know if that was done correctly.

### CODE REVIEW

**Comment by blshkv** [comment]
LOL, you really need to read manual ;-)
```ebuild pwncat-0.1.0.ebuild manifest``` does it

**Comment by blshkv** [comment]
also, please keep a previous version in place just in case if a newer version has new bugs, which is the case very often.

**Comment by blshkv** [comment]
I just realised that you are the author of this tool, not a pentoo user probably, and submitted similar requests to other distributions. That's quite an effort! I have subscribed to monitor new releases and will help to bump it next time.
Thanks!

**Comment by cytopia** [comment]
> I just realised that you are the author of this tool, not a pentoo user probably, and submitted similar requests to other distributions. That's quite an effort! I have subscribed to monitor new releases and will help to bump it next time.
> Thanks!

Thanks for the help. That was actually quite some struggle figuring out what distros have it, where to submit package changes and even how to do that :sweat:

**Pull request merged**
