### PR TITLE
dev-util/plasma: A start to close issue #337.

### PR DESCRIPTION
**Pull request by ephemer0l**
ebuilds not tested

Package-Manager: Portage-2.3.40, Repoman-2.3.9

### CODE REVIEW

**Comment by blshkv** [comment]
Please test before pulling

**Comment by ephemer0l** [comment]
Tested and works with python 3.6

**Comment by necrose99** [comment]
built from checkout branch , 
(as atm https://bugs.gentoo.org/show_bug.cgi?id=664220)
being that capstone:4 is required yet not done.. for arm64/arm builds..   and atm requires in radare2 capstone for arm... dev-libs/keystone-0.9.1::gentoo  
ebuild dev-util/plasma/plasma-0_p21080708.ebuild package , emerge to tarball....

**Comment by necrose99** [comment]
scw-0321f9 /usr/bin # plasma -i zip
error: arch AArch64 is not supported
scw-0321f9 /usr/bin #
https://www.dropbox.com/s/zm13xm0chwlos7k/plasma-9999.tbz2?dl=0  bin out...

**Comment by blshkv** [comment]
ok, cool. Let's pull it into our try for testing.
Thanks!

**Pull request merged**
