### PR TITLE
fchroot from Funtoo core kit, ez chroot to arm64/arm/riscv rootfs , fixed gpg snafu. 

### PR DESCRIPTION
**Pull request by necrose99**
sys-apps/fchroot on funtoo ,  added to app-emu.. 
for less a problem in using the overlay compatibility  with upstream 
rebase /reset to un bork this item. 

at worst one can use x86-64-static /mnt/pentoo-arm64/usr/local/bin/ 
https://github.com/multiarch/qemu-user-static > 
even from live usb..  the python setup chroot and qemu exec wrapper and all the fuss..
`fchoot /mnt/pentoo-arm64 `
`chroot /mnt/pentoo-arm64`  and vol'a 
fchroot-on-pentoo my victabox vm 

**since hwsetup is dead** i need a [g213](https://github.com/SebiTimeWaster/G213Colors) /[USBRESET ](https://github.com/jkulesza/usbreset)init script  for the real pentoo install 
I'm not wanting to drag out tower to jiggle damb kb cable. 
 and its sunday time to slay some mobs and eat dinner.

### CODE REVIEW

**Comment by blshkv** [comment]
I think you are fixing a wrong problem. Are you facing the issue on the sreenshot? Just adjust flags

**Comment by necrose99** [comment]
_https://www.funtoo.org/Arm64_generic_ ,  **kicking the tires hear**  
 tends to hate my not so modified gentoo arm64 make.conf  funtoo nests profiles like russian dolls  in fact thier make.conf is often blank.. 
ig python targets 36,37,38,39 , 37 single targets   funtoo likes a defacto mono y mono python ... 

on rpi4 arm64 gentoo  there are times eselect python list/set is a life saver / revdep-rebuild 
usb plugged /microsd to vm for rpi 4 for gits n shingles
**emerge eix  ok...** 
**emerge xfce4-meta** , then it grinds to a halt .. missing or broken/half baked  deps on arm64 ..  ala funtoo   elogind and gives deps hell i did care to ...  

test **fchroot** works , and walla  funtoo + usual overlys not so much... 
_core-kit / sys-apps/fchroot ,, least i fished ebuild out ..._ 


https://github.com/sakaki-/gentoo-on-rpi-64bit despite  her eol due to job   embargo per contract to open source projects. 
i /others have forked it..  to org s ..

the profiles etc  and meta ebuilds for most part work .  emerge pentoo  symlink to etc/portage 
https://github.com/pentoo/pentoo-overlay/blob/master/profiles/package.mask 
https://github.com/pentoo/pentoo-overlay/tree/master/profiles/pentoo/bleeding 

arm64 generic profile should be easy enough. 
rpi4 can steal it , prune off mono 6 mask i have already built it.

**Comment by blshkv** [comment]
<blshvk> SRC_URI is wrong, keywords are not there
[discord] <Zero_Chaos> That * is pretty ugly though, I wouldn't accept that.
[irc] <dwfreed> their ebuild is wrong :P
[irc] <dwfreed> also missing newline at the end of the file
[irc] <dwfreed> also the PYTHON_COMPAT is wrong
[irc] <dwfreed> also because this is a program and not a module, it should be using DISTUTILS_SINGLE_IMPL
[irc] <dwfreed> so you need to adjust it because that's obviously not available outside of funtoo

**Comment by necrose99** [comment]
clean up on package done. [commit](https://github.com/necrose99/pentoo-overlay/commit/048fa359305880cde55de58312f98ebcac2cbef2)  

the tarball builds in vmware fine, now to test this thing.    , but first clean out of of vmware image of it. 
test against my Gentoo arm64/pentoo pkgs..  rpi on 256 gig sd card....  over usb..

**Comment by blshkv** [comment]
I gave up. After so many rounds you still can't provide a working ebuild, it doesn't even compiles. DO NOT SUBMIT BROKEN ebuilds.
```
Invalid implementation in PYTHON_COMPAT: python3_10
```

**Comment by necrose99** [comment]
**with thanksgiving holiday i've been cooking food..** 
wifes good at banking not as much but for cooking a few things so back to slaving the stove. 

for now i staged for me to fiddle , (yara-python for skeleton ) tends to run ,[python3_10 beta soonish /alpha](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-lang/python/python-3.10.0_alpha1.ebuild) but 
_blink and it be stable... all too soon..  and rammed to officially over 3.8_  

but i can remove 10 if it wont 
mays well ..  teast em all..  
url handler at worse i can link straight to tarball  , it was linked prior it should do  , though tends to get the frown .. 

**got pies to bake , steaks to grill**

**Comment by blshkv** [comment]
oh, 3_10 is in the tree. Ok, sorry. Let's try to merge it

**Pull request merged**
