### PR TITLE
bettercap: bump to v1.5.4

### PR DESCRIPTION
**Pull request by mudler**

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
please don't restrict mirror unless mirroring is disallowed.  yes, I know it speeds things up if they are not in the gentoo mirrors but it causes problems when I try to merge ebuilds into gentoo and have no idea why that is there.

**Comment by mudler** [comment]
@ZeroChaos- sure

**Comment by ZeroChaos-** [comment]
@mudler thanks!

**Comment by blshkv** [comment]
Guys please do not commit it half way. You deleted the previous ebuild without adjusting keywords. That  broke the tree

**Pull request merged**
