### PR TITLE
app-admin/opensnitch{,-ebpf-module}: add 1.6.5_p1

### PR DESCRIPTION
**Pull request by kcning**

### CODE REVIEW

**Comment by blshkv** [comment]
Hi, the upstream released 1.6.5.1, it must be some urgent fix. Could you bump it instead?
Also, we have new checks, could you please fix it too

**Comment by kcning** [comment]
> Hi, the upstream released 1.6.5.1, it must be some urgent fix. Could you bump it instead?

Certainly, I'll bump it.

About the error message:
```version 1.6.5: uses deprecated eclass: golang-vcs-snapshot (migrate to go-module.eclass)```
I can try to migrate to go-module.eclass, but it will take some time.

**Comment by kcning** [comment]
The ebuild has been migrated to using ```go-module.eclass```. Right now, the dependency tar ball is hosted on a repo that I own. If you would like to host the tar ball on the Pentoo website (or somewhere else) instead, please go ahead. For example, if you can create another Github repo.

**Comment by blshkv** [comment]
that's an interesting point about hosting. So far, we have been using ```pentoo.org/~home```, similar to Gentoo. However, it is not contributors friendly. It would be easier to have a separate github repository. @ZeroChaos- what do you think?

**Comment by ZeroChaos-** [comment]
I don't mean anything specific to this PR but I am against accepting random tarballs into a git repo as a general rule.

**Comment by blshkv** [comment]
give me a few minutes, I'm regenerating it. It was just easier to accept the pull and adjust it later

**Comment by kcning** [comment]
Thank you for quickly merging this PR. I understand that accepting tarballs can be a security risk, because of the amount of code that needs to be reviewed. Regenerating the tarballs is indeed better, and I wouldn't need to maintain this extra repo for deps.

**Pull request merged**
