### PR TITLE
rekall ebuilds

### PR DESCRIPTION
**Pull request by ostree**
re: [ebuild request] add "rekall" forensic tool #2
Memory Forensic Framework http://www.rekall-forensic.com

### CODE REVIEW

**Comment by ostree** [comment]
needs testing

**Comment by blshkv** [comment]
Thanks for creating the pull. That was in my todo list:
https://github.com/pentoo/pentoo-overlay/issues/2

**Comment by ostree** [comment]
unfortunately I am not able to test because the kernel version and I came across a problem: 
pkg_resources.DistributionNotFound: efilter==1438631774

**Comment by blshkv** [comment]
Finish your job and fix it ;-)

**Comment by ostree** [comment]
Yeah, looks like we need google/dotty (EFILTER Query Language) too and other deps ;)

**Pull request merged**
