### PR TITLE
dev-python/grpcio{,-tools}: add 1.65.2

### PR DESCRIPTION
**Pull request by kcning**

### CODE REVIEW

**Comment by blshkv** [comment]
Hi, could you clarify why some options are not used, for example, the following were removed:
ihnerit multiprocessing prefix
```GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS```
also, cython ( "${FILESDIR}/1.62.0-cython3.patch" )

**Comment by kcning** [comment]
Yes, certainly. I should have explained. Apology for that. The motivation for this PR though, is because version 1.62.0 blocks dev-python/protobuf-python-5. Those small (cosmetic) changes were not the main reason.

1. The patch is no longer needed because the upstream [fixed](https://github.com/grpc/grpc/commit/4bea12353c2f0f5a52746821f1e3f961592c7ca0) the issue 
2. Without setting GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS, it builds with all the cores already. I tested and setting it doesn't speed up the compilation, so I dropped multiprocessing.eclasss. If you'd like to keep it. Please feel free to do so.
3. I dropped prefix.eclass because ```hprefixify``` doesn't seem necessary. Likewise, please feel free to keep it.

**Comment by blshkv** [comment]
Fails to compile here. I have not tried to figure out what's going on..

```
./src/core/lib/promise/pipe.h: In instantiation of ‘void grpc_core::pipe_detail::Center<T>::Unref() [with T = std::unique_ptr<grpc_core::Message, grpc_core::Arena::PooledDeleter>]’:
./src/core/lib/gprpp/ref_counted_ptr.h:113:41:   required from ‘grpc_core::RefCountedPtr<T>::~RefCountedPtr() [with T = grpc_core::pipe_detail::Center<std::unique_ptr<grpc_core::Message, grpc_core::Arena::PooledDeleter> >]’
./src/core/lib/promise/pipe.h:556:29:   required from ‘auto grpc_core::PipeReceiver<T>::Next() [with T = std::unique_ptr<grpc_core::Message, grpc_core::Arena::PooledDeleter>]’
./src/core/lib/promise/pipe.h:677:75:   required by substitution of ‘template<class T> using grpc_core::PipeReceiverNextType = decltype (declval<grpc_core::PipeReceiver<T> >().Next()) [with T = std::unique_ptr<grpc_core::Message, grpc_core::Arena::PooledDeleter>]’
./src/core/lib/channel/promise_based_filter.h:1161:41:   required from here
./src/core/lib/debug/trace_impl.h:85:44: error: ‘VLOG’ was not declared in this scope; did you mean ‘LOG’?
   85 |   if (GRPC_TRACE_FLAG_ENABLED(tracer)) VLOG(level)
      |                                        ~~~~^~~~~~~
./src/core/lib/promise/pipe.h:135:5: note: in expansion of macro ‘GRPC_TRACE_VLOG’
  135 |     GRPC_TRACE_VLOG(promise_primitives, 2) << DebugOpString("Unref");
      |     ^~~~~~~~~~~~~~~
2024-08-02 19:38:09,614 root INFO creating var
2024-08-02 19:38:09,614 root INFO creating var/tmp
2024-08-02 19:38:09,614 root INFO creating var/tmp/portage
2024-08-02 19:38:09,614 root INFO creating var/tmp/portage/dev-python
2024-08-02 19:38:09,614 root INFO creating var/tmp/portage/dev-python/grpcio-1.65.2
2024-08-02 19:38:09,614 root INFO creating var/tmp/portage/dev-python/grpcio-1.65.2/temp
2024-08-02 19:38:09,615 root INFO creating var/tmp/portage/dev-python/grpcio-1.65.2/temp/tmptaluc852
2024-08-02 19:38:09,615 root INFO x86_64-pc-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -O2 -pipe -frecord-gcc-switches -DNDEBUG -fPIC -I/usr/include/python3.12 -c /var/tmp/portage/dev-python/grpcio-1.65.2/temp/tmptaluc852/a.c -o var/tmp/portage/dev-python/grpcio-1.65.2/temp/tmptaluc852/a.o
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/spawn.py", line 71, in spawn
    subprocess.check_call(cmd, env=_inject_macos_ver(env))
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/x86_64-pc-linux-gnu-gcc', '-fno-strict-overflow', '-Wsign-compare', '-DNDEBUG', '-O2', '-pipe', '-frecord-gcc-switches', '-DNDEBUG', '-fPIC', '-D_WIN32_WINNT=1536', '-DGRPC_XDS_USER_AGENT_NAME_SUFFIX="Python"', '-DGRPC_XDS_USER_AGENT_VERSION_SUFFIX="1.65.2"', '-DOPENSSL_NO_ASM=1', '-DHAVE_CONFIG_H=1', '-DGRPC_ENABLE_FORK_SUPPORT=1', '-DGRPC_DO_NOT_INSTANTIATE_POSIX_POLLER=1', '-D__STDC_FORMAT_MACROS', '-DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject*', '-DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1', '-Isrc/python/grpcio', '-Iinclude', '-I.', '-I/usr/include', '-Ithird_party/address_sorting/include', '-I/usr/include', '-I/usr/include/re2', '-I/usr/include/openssl', '-Ithird_party/upb', '-Isrc/core/ext/upb-gen', '-Isrc/core/ext/upbdefs-gen', '-Ithird_party/utf8_range', '-Ithird_party/xxhash', '-I/usr/include', '-I/usr/include/python3.12', '-c', 'src/core/client_channel/client_channel.cc', '-o', '/var/tmp/portage/dev-python/grpcio-1.65.2/work/grpcio-1.65.2-python3_12/build/temp.linux-x86_64-cpython-312/src/core/client_channel/client_channel.o', '-std=c++14', '-fvisibility=hidden', '-fno-wrapv', '-fno-exceptions', '-pthread']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 191, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
  File "/var/tmp/portage/dev-python/grpcio-1.65.2/work/grpcio-1.65.2/src/python/grpcio/_spawn_patch.py", line 58, in _commandfile_spawn
    _classic_spawn(self, command, **kwargs)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/ccompiler.py", line 1044, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/spawn.py", line 77, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/grpcio-1.65.2/work/grpcio-1.65.2/src/python/grpcio/commands.py", line 313, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 477, in build_extensions
    self._build_extensions_parallel()
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 500, in _build_extensions_parallel
    fut.result()
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.12/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/ccompiler.py", line 605, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 193, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 443, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 439, in main
    return func(args)
           ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 229, in build_wheel
    print(build_wheel_impl(args, args.wheel_dir), file=out)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 221, in build_wheel_impl
    wheel_name = backend.build_wheel(str(wheel_dir), args.config_json)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 415, in build_wheel
    return self._build_with_temp_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
    self.run_setup()
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
    exec(code, locals())
  File "<string>", line 579, in <module>
  File "/usr/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 974, in run_command
    super().run_command(command)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
    self.run_command("build")
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 974, in run_command
    super().run_command(command)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 974, in run_command
    super().run_command(command)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 93, in run
    _build_ext.run(self)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/var/tmp/portage/dev-python/grpcio-1.65.2/work/grpcio-1.65.2/src/python/grpcio/commands.py", line 317, in build_extensions
    raise CommandError(
commands.CommandError: Failed `build_ext` step:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/spawn.py", line 71, in spawn
    subprocess.check_call(cmd, env=_inject_macos_ver(env))
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/x86_64-pc-linux-gnu-gcc', '-fno-strict-overflow', '-Wsign-compare', '-DNDEBUG', '-O2', '-pipe', '-frecord-gcc-switches', '-DNDEBUG', '-fPIC', '-D_WIN32_WINNT=1536', '-DGRPC_XDS_USER_AGENT_NAME_SUFFIX="Python"', '-DGRPC_XDS_USER_AGENT_VERSION_SUFFIX="1.65.2"', '-DOPENSSL_NO_ASM=1', '-DHAVE_CONFIG_H=1', '-DGRPC_ENABLE_FORK_SUPPORT=1', '-DGRPC_DO_NOT_INSTANTIATE_POSIX_POLLER=1', '-D__STDC_FORMAT_MACROS', '-DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject*', '-DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1', '-Isrc/python/grpcio', '-Iinclude', '-I.', '-I/usr/include', '-Ithird_party/address_sorting/include', '-I/usr/include', '-I/usr/include/re2', '-I/usr/include/openssl', '-Ithird_party/upb', '-Isrc/core/ext/upb-gen', '-Isrc/core/ext/upbdefs-gen', '-Ithird_party/utf8_range', '-Ithird_party/xxhash', '-I/usr/include', '-I/usr/include/python3.12', '-c', 'src/core/client_channel/client_channel.cc', '-o', '/var/tmp/portage/dev-python/grpcio-1.65.2/work/grpcio-1.65.2-python3_12/build/temp.linux-x86_64-cpython-312/src/core/client_channel/client_channel.o', '-std=c++14', '-fvisibility=hidden', '-fno-wrapv', '-fno-exceptions', '-pthread']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 191, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
  File "/var/tmp/portage/dev-python/grpcio-1.65.2/work/grpcio-1.65.2/src/python/grpcio/_spawn_patch.py", line 58, in _commandfile_spawn
    _classic_spawn(self, command, **kwargs)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/ccompiler.py", line 1044, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/spawn.py", line 77, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/grpcio-1.65.2/work/grpcio-1.65.2/src/python/grpcio/commands.py", line 313, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 477, in build_extensions
    self._build_extensions_parallel()
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 500, in _build_extensions_parallel
    fut.result()
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.12/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/ccompiler.py", line 605, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 193, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1
```

**Comment by blshkv** [comment]
```
2024-08-02 19:37:59,294 root INFO creating /var/tmp/portage/dev-python/grpcio-1.65.2/work/grpcio-1.65.2-python3_12/build/temp.linux-x86_64-cpython-312/third_party/utf8_range
2024-08-02 19:37:59,294 root INFO x86_64-pc-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -O2 -pipe -frecord-gcc-switches -DNDEBUG -fPIC -D_WIN32_WINNT=1536 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"Python\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.65.2\" -DOPENSSL_NO_ASM=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DGRPC_DO_NOT_INSTANTIATE_POSIX_POLLER=1 -D__STDC_FORMAT_MACROS "-DPyMODINIT_FUNC=extern \"C\" __attribute__((visibility (\"default\"))) PyObject*" -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -I/usr/include -Ithird_party/address_sorting/include -I/usr/include -I/usr/include/re2 -I/usr/include/openssl -Ithird_party/upb -Isrc/core/ext/upb-gen -Isrc/core/ext/upbdefs-gen -Ithird_party/utf8_range -Ithird_party/xxhash -I/usr/include -I/usr/include/python3.12 -c src/core/channelz/channel_trace.cc -o /var/tmp/portage/dev-python/grpcio-1.65.2/work/grpcio-1.65.2-python3_12/build/temp.linux-x86_64-cpython-312/src/core/channelz/channel_trace.o -std=c++14 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
2024-08-02 19:38:00,911 root INFO x86_64-pc-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -O2 -pipe -frecord-gcc-switches -DNDEBUG -fPIC -D_WIN32_WINNT=1536 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"Python\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.65.2\" -DOPENSSL_NO_ASM=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DGRPC_DO_NOT_INSTANTIATE_POSIX_POLLER=1 -D__STDC_FORMAT_MACROS "-DPyMODINIT_FUNC=extern \"C\" __attribute__((visibility (\"default\"))) PyObject*" -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -I/usr/include -Ithird_party/address_sorting/include -I/usr/include -I/usr/include/re2 -I/usr/include/openssl -Ithird_party/upb -Isrc/core/ext/upb-gen -Isrc/core/ext/upbdefs-gen -Ithird_party/utf8_range -Ithird_party/xxhash -I/usr/include -I/usr/include/python3.12 -c src/core/channelz/channelz.cc -o /var/tmp/portage/dev-python/grpcio-1.65.2/work/grpcio-1.65.2-python3_12/build/temp.linux-x86_64-cpython-312/src/core/channelz/channelz.o -std=c++14 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
2024-08-02 19:38:03,614 root INFO x86_64-pc-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -O2 -pipe -frecord-gcc-switches -DNDEBUG -fPIC -D_WIN32_WINNT=1536 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"Python\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.65.2\" -DOPENSSL_NO_ASM=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DGRPC_DO_NOT_INSTANTIATE_POSIX_POLLER=1 -D__STDC_FORMAT_MACROS "-DPyMODINIT_FUNC=extern \"C\" __attribute__((visibility (\"default\"))) PyObject*" -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -I/usr/include -Ithird_party/address_sorting/include -I/usr/include -I/usr/include/re2 -I/usr/include/openssl -Ithird_party/upb -Isrc/core/ext/upb-gen -Isrc/core/ext/upbdefs-gen -Ithird_party/utf8_range -Ithird_party/xxhash -I/usr/include -I/usr/include/python3.12 -c src/core/channelz/channelz_registry.cc -o /var/tmp/portage/dev-python/grpcio-1.65.2/work/grpcio-1.65.2-python3_12/build/temp.linux-x86_64-cpython-312/src/core/channelz/channelz_registry.o -std=c++14 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
2024-08-02 19:38:05,458 root INFO x86_64-pc-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -O2 -pipe -frecord-gcc-switches -DNDEBUG -fPIC -D_WIN32_WINNT=1536 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"Python\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.65.2\" -DOPENSSL_NO_ASM=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DGRPC_DO_NOT_INSTANTIATE_POSIX_POLLER=1 -D__STDC_FORMAT_MACROS "-DPyMODINIT_FUNC=extern \"C\" __attribute__((visibility (\"default\"))) PyObject*" -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -I/usr/include -Ithird_party/address_sorting/include -I/usr/include -I/usr/include/re2 -I/usr/include/openssl -Ithird_party/upb -Isrc/core/ext/upb-gen -Isrc/core/ext/upbdefs-gen -Ithird_party/utf8_range -Ithird_party/xxhash -I/usr/include -I/usr/include/python3.12 -c src/core/client_channel/backup_poller.cc -o /var/tmp/portage/dev-python/grpcio-1.65.2/work/grpcio-1.65.2-python3_12/build/temp.linux-x86_64-cpython-312/src/core/client_channel/backup_poller.o -std=c++14 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
2024-08-02 19:38:06,368 root INFO x86_64-pc-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -O2 -pipe -frecord-gcc-switches -DNDEBUG -fPIC -D_WIN32_WINNT=1536 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"Python\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.65.2\" -DOPENSSL_NO_ASM=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DGRPC_DO_NOT_INSTANTIATE_POSIX_POLLER=1 -D__STDC_FORMAT_MACROS "-DPyMODINIT_FUNC=extern \"C\" __attribute__((visibility (\"default\"))) PyObject*" -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -I/usr/include -Ithird_party/address_sorting/include -I/usr/include -I/usr/include/re2 -I/usr/include/openssl -Ithird_party/upb -Isrc/core/ext/upb-gen -Isrc/core/ext/upbdefs-gen -Ithird_party/utf8_range -Ithird_party/xxhash -I/usr/include -I/usr/include/python3.12 -c src/core/client_channel/client_channel.cc -o /var/tmp/portage/dev-python/grpcio-1.65.2/work/grpcio-1.65.2-python3_12/build/temp.linux-x86_64-cpython-312/src/core/client_channel/client_channel.o -std=c++14 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
In file included from ./src/core/lib/resource_quota/memory_quota.h:46,
                 from ./src/core/lib/resource_quota/arena.h:40,
                 from ./src/core/lib/promise/arena_promise.h:32,
                 from ./src/core/lib/transport/transport.h:51,
                 from ./src/core/client_channel/connector.h:31,
                 from ./src/core/client_channel/subchannel.h:34,
                 from ./src/core/client_channel/client_channel_factory.h:24,
                 from ./src/core/client_channel/client_channel.h:26,
                 from src/core/client_channel/client_channel.cc:17:
./src/core/lib/promise/activity.h: In member function ‘std::string grpc_core::Waker::DebugString()’:
./src/core/lib/promise/activity.h:126:18: error: ‘StrFormat’ is not a member of ‘absl’
  126 |     return absl::StrFormat("Waker{%p, %d}", wakeable_and_arg_.wakeable,
      |                  ^~~~~~~~~
In file included from ./src/core/lib/promise/seq.h:27,
                 from ./src/core/lib/promise/pipe.h:42,
                 from ./src/core/lib/transport/transport.h:54:
./src/core/lib/promise/detail/seq_state.h: In member function ‘grpc_core::Poll<typename Traits<typename grpc_core::promise_detail::OncePromiseFactory<typename Traits<typename grpc_core::promise_detail::PromiseLike<F>::Result>::UnwrappedType, F0>::Promise::Result>::WrappedType> grpc_core::promise_detail::SeqState<Traits, P, F0>::PollOnce()’:
./src/core/lib/promise/detail/seq_state.h:147:11: error: there are no arguments to ‘VLOG’ that depend on a template parameter, so a declaration of ‘VLOG’ must be available [-fpermissive]
  147 |           VLOG(2).AtLocation(whence.file(), whence.line())
      |           ^~~~
./src/core/lib/promise/detail/seq_state.h:147:11: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
./src/core/lib/promise/detail/seq_state.h:153:11: error: there are no arguments to ‘VLOG’ that depend on a template parameter, so a declaration of ‘VLOG’ must be available [-fpermissive]
  153 |           VLOG(2).AtLocation(whence.file(), whence.line())
      |           ^~~~
./src/core/lib/promise/detail/seq_state.h:180:11: error: there are no arguments to ‘VLOG’ that depend on a template parameter, so a declaration of ‘VLOG’ must be available [-fpermissive]
  180 |           VLOG(2).AtLocation(whence.file(), whence.line())
      |           ^~~~
./src/core/lib/promise/detail/seq_state.h:185:11: error: there are no arguments to ‘VLOG’ that depend on a template parameter, so a declaration of ‘VLOG’ must be available [-fpermissive]
  185 |           VLOG(2).AtLocation(whence.file(), whence.line())
```

**Comment by blshkv** [comment]
https://pastebin.com/gn5VkYRw

**Comment by blshkv** [comment]
I'm not able to upgrade dev-libs/re2-0.2024.07.02, see https://bugs.gentoo.org/937131 
The error looks similar

**Comment by blshkv** [comment]
ok, merged. Feel free to test and let me know if it works
https://github.com/pentoo/pentoo-overlay/pull/2061

**Comment by kcning** [comment]
Hi, the missing macro was introduced to abseil-cpp by this [commit](https://github.com/abseil/abseil-cpp/commit/7b6c17e378224844d8663a410da2da5353b205b9). So version 1.65.2 depends on ```>=dev-cpp/abseil-cpp-20240116```  A fix would be sth like this:
```
BDEPEND="
    virtual/pkgconfig
    dev-python/cython[${PYTHON_USEDEP}]
"
RDEPEND="
    >=dev-libs/openssl-1.1.1:0=[-bindist(-)]
    >=dev-python/protobuf-python-5.26.1[${PYTHON_USEDEP}]
    >=dev-libs/re2-0.2024.07.02:=
    >=dev-cpp/abseil-cpp-20240116
    net-dns/c-ares:=
    sys-libs/zlib:=
"
DEPEND="
    ${RDEPEND}
"
```

**Comment by kcning** [comment]
It shouldn't have been an issued tho, because dev-libs/re2-0.2024.07.02 depends on >=dev-cpp/abseil-cpp-20240116 already.

**Comment by kcning** [comment]
> ok, merged. Feel free to test and let me know if it works #2061

It builds, thank you!

**Comment by blshkv** [comment]
great, thanks. I'll review it again once a newer version of protobuf is stable.

**Pull request closed without merging**
