### PR TITLE
getsploit: new tool

### PR DESCRIPTION
**Pull request by linxon**

### CODE REVIEW

**Comment by blshkv** [comment]
Let's merge it first, I'll check it later

**Comment by blshkv** [comment]
Can you sign your commit please? I'm unable to merge it with single button click.

**Comment by blshkv** [comment]
Also, could you try to commit your patch (user home support) to upstream? It's a really good thing to have, but we don't want to maintain it if possible

**Comment by linxon** [comment]
> could you try to commit your patch (user home support) to upstream

well... i'm create a pull request as: https://github.com/vulnersCom/getsploit/pull/14

**Comment by blshkv** [comment]
Well done, thanks! I looked at issues only and missed the pull request

**Pull request merged**
