### PR TITLE
adding LinEnum ebuild for #235

### PR DESCRIPTION
**Pull request by gkroon**
Used nikto ebuild as a guideline, but please let me know if I need to fix anything.

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
I'm not sure it needs to be installed twice, maybe pick a name and stick with it?

**Comment by gkroon** [comment]
I was thinking the same, but then I saw [Nikto](https://github.com/pentoo/pentoo-overlay/tree/master/net-analyzer/nikto) is doing the same. Would you still like me to remove one?

**Comment by ZeroChaos-** [comment]
yes please

**Comment by gkroon** [comment]
No problem, I fixed the redundant symlink issue. Anything else you want me to change?

**Comment by blshkv** [comment]
done, thanks!

**Pull request merged**
