### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by necrose99**
http://data.gpo.zugaina.org/fkmclane/net-proxy/mitmproxy/mitmproxy-2.0.2.ebuild

newer , leave old for now...

### CODE REVIEW

**Comment by blshkv** [comment]
We don't have half of dependencies. Please test before creating a pull

**Comment by necrose99** [comment]
ok.... that 1  has far to many ... depends... 
... , I can test-bump the existing ebuild.. as mitmproxy-2.0.2.ebuild and piddle with it when I get home.
@LSD if I use that theirs...

my bad didn't realize you had wifi pumpkin already..

**Comment by blshkv** [comment]
create a new pull when you have a working ebuild with updated dependencies

**Comment by necrose99** [comment]
so far in osboxes.org sabayon -VM some of the pentoo dev/python are not building due to fetch errors. 
going to just pull the bins...  over ftp .. 

#/var/lib...//pentoo/....       net-proxy/mitmproxy/mitmproxy-2.0.2.ebuild   clone (pentoo 1.x)  and manifested ebuild... 
now just if the deps would co-operate... :-(  

fkmclane  mitmproxy-2.0.2.ebuild  has a few to many deps..   any-rate I'll pull the ftp deps via pentoo mirror , and give it a go this evening.  for test bump ..

**Pull request closed without merging**
