### PR TITLE
xsstrike: 3.1.4 bump + small fixes

### PR DESCRIPTION
**Pull request by gkroon**
I noticed xsstrike didn't work anymore due to missing plugins folder. I also did some minor fixes.

### CODE REVIEW

**Comment by blshkv** [comment]
can you review small fixes? https://github.com/pentoo/pentoo-overlay/commit/6d698c17e0794f04cf50778dc00320c6e6b136ee

**Comment by blshkv** [comment]
please do not create that additional file in filesdir, it is possible to avoid it and use lesser space

**Comment by blshkv** [comment]
nevermind, I'm fixing it

**Comment by gkroon** [comment]
> please do not create that additional file in filesdir, it is possible to avoid it and use lesser space

Sorry, I'll remember for next time.

> nevermind, I'm fixing it

Thanks!

**Pull request closed without merging**
