### PR TITLE
Add SDRPlusPlus

### PR DESCRIPTION
**Pull request by drsn0w**
## Add SDRPlusPlus
Ebuild name is `net-wireless/sdrpp`

### Versions
- 1.0.4
- 9999 (build directly from git repo)

### Dependancies
- `sci-libs/fftw`
- `media-libs/glew`
- `media-libs/glfw`
- `sci-libs/volk`

### USE Flags
(* denotes enabled by default)
- `airspy`: include support for AirSpy devices (requires `net-wireless/airspy`)
- `bladerf`: include support for BladeRF devices (requires `net-wireless/bladerf`)
- `hackrf`: include support for HackRF devices (requires `net-wireless/libhackrf`)
- `limesdr`: include support for LimeSDR devices (requires `net-wireless/limesuite`)
- `plutosdr`: include support for PlutoSDR devices (requires `net-libs/libiio` and `net-libs/libad9361-iio`
- *`rtlsdr`: include support for RTLSDR devices (requires `net-wireless/rtl-sdr`)
- `soapysdr`: includes support for SoapySDR devices (requires `net-wireless/soapysdr`)
- `spyserver`: includes support for input from SpyServer (no local requirements)
- *`audiosink`: supports outputting via ALSA/PulseAudio (requires `media-libs/rtaudio`)
- `portaudio`: supports outputting via Portaudio (requires `media-libs/portaudio`)
- `discord`: enables Discord rich presence support

### Patches
Included is a patch to make cmake use `${CMAKE_INSTALL_FULL_LIBDIR}` instead of hardcoding `lib` in order to conform to Gentoo's strict multilib standards (32-bit libs in `lib` and 64-bit libs in `lib64`) and stop Portage from complaining. Two patches are included, one for v1.0.4 and one for 9999 as they vary slightly.

I hope to provide maintenance and version bumps for the ebuild as I can. I can only test on `amd64`.

### CODE REVIEW

**Comment by blshkv** [comment]
Cool, thanks

**Comment by ZeroChaos-** [comment]
Thanks!

**Comment by chron0** [comment]
Hi, thanks for sharing an sdrpp ebuild, I've tried this ebuild but the plugins arent being picked up by sdrpp:

```
[2022-04-20 14:26:28.880] [info] SDR++ v1.0.4
[2022-04-20 14:26:28.880] [info] Loading config
[2022-04-20 14:26:28.881] [warning] ConfigManager locked, waiting...
[2022-04-20 14:26:28.934] [info] Using OpenGL 3.0
[2022-04-20 14:26:29.044] [info] Loading icons
[2022-04-20 14:26:29.055] [info] Loading band plans
[2022-04-20 14:26:29.062] [info] Loading band plans color table
[2022-04-20 14:26:29.073] [info] Loading modules
[2022-04-20 14:26:29.073] [warning] Module directory /usr/lib/sdrpp/plugins does not exist, not loading modules from directory
[2022-04-20 14:26:29.073] [info] Initializing Airspy Source (airspy_source)
[2022-04-20 14:26:29.082] [error] Module 'airspy_source' doesn't exist
[2022-04-20 14:26:29.082] [info] Initializing AirspyHF+ Source (airspyhf_source)
[2022-04-20 14:26:29.099] [error] Module 'airspyhf_source' doesn't exist
[2022-04-20 14:26:29.099] [info] Initializing Audio Sink (audio_sink)
[2022-04-20 14:26:29.116] [error] Module 'audio_sink' doesn't exist
[2022-04-20 14:26:29.116] [info] Initializing BladeRF Source (bladerf_source)
[2022-04-20 14:26:29.132] [error] Module 'bladerf_source' doesn't exist
[2022-04-20 14:26:29.132] [info] Initializing File Source (file_source)
[2022-04-20 14:26:29.149] [error] Module 'file_source' doesn't exist
[2022-04-20 14:26:29.149] [info] Initializing Frequency Manager (frequency_manager)
[2022-04-20 14:26:29.166] [error] Module 'frequency_manager' doesn't exist
[2022-04-20 14:26:29.166] [info] Initializing HackRF Source (hackrf_source)
[2022-04-20 14:26:29.182] [error] Module 'hackrf_source' doesn't exist
[2022-04-20 14:26:29.183] [info] Initializing LimeSDR Source (limesdr_source)
[2022-04-20 14:26:29.199] [error] Module 'limesdr_source' doesn't exist
[2022-04-20 14:26:29.199] [info] Initializing Network Sink (network_sink)
[2022-04-20 14:26:29.216] [error] Module 'network_sink' doesn't exist
[2022-04-20 14:26:29.216] [info] Initializing PlutoSDR Source (plutosdr_source)
[2022-04-20 14:26:29.232] [error] Module 'plutosdr_source' doesn't exist
[2022-04-20 14:26:29.233] [info] Initializing RTL-SDR Source (rtl_sdr_source)
[2022-04-20 14:26:29.249] [error] Module 'rtl_sdr_source' doesn't exist
[2022-04-20 14:26:29.249] [info] Initializing RTL-TCP Source (rtl_tcp_source)
[2022-04-20 14:26:29.266] [error] Module 'rtl_tcp_source' doesn't exist
[2022-04-20 14:26:29.266] [info] Initializing Radio (radio)
[2022-04-20 14:26:29.282] [error] Module 'radio' doesn't exist
[2022-04-20 14:26:29.283] [info] Initializing Recorder (recorder)
[2022-04-20 14:26:29.300] [error] Module 'recorder' doesn't exist
[2022-04-20 14:26:29.300] [info] Initializing Rigctl Server (rigctl_server)
[2022-04-20 14:26:29.316] [error] Module 'rigctl_server' doesn't exist
[2022-04-20 14:26:29.316] [info] Initializing SDRplay Source (sdrplay_source)
[2022-04-20 14:26:29.333] [error] Module 'sdrplay_source' doesn't exist
[2022-04-20 14:26:29.333] [info] Initializing SoapySDR Source (soapy_source)
[2022-04-20 14:26:29.349] [error] Module 'soapy_source' doesn't exist
[2022-04-20 14:26:29.350] [info] Initializing SpyServer Source (spyserver_source)
[2022-04-20 14:26:29.366] [error] Module 'spyserver_source' doesn't exist
```

I can find the plugins in /usr/lib64/sdrpp/plugins but it seems sdrpp still expects them in /usr/lib/sdpp/plugins
The cmake patchfile for 1.0.4 gives me this during the build:

```
>>> Preparing source in /var/tmp/portage/net-wireless/sdrpp-1.0.4/work/SDRPlusPlus-1.0.4 ...
 * Applying fix-cmake-libdir-location-1.0.4.patch ...
patching file CMakeLists.txt
patching file core/CMakeLists.txt
Hunk #1 succeeded at 106 (offset -11 lines).
patching file decoder_modules/falcon9_decoder/CMakeLists.txt
patching file decoder_modules/m17_decoder/CMakeLists.txt
patching file decoder_modules/meteor_demodulator/CMakeLists.txt
patching file decoder_modules/radio/CMakeLists.txt
patching file decoder_modules/weather_sat_decoder/CMakeLists.txt
patching file misc_modules/demo_module/CMakeLists.txt
patching file misc_modules/discord_integration/CMakeLists.txt
patching file misc_modules/frequency_manager/CMakeLists.txt
patching file misc_modules/recorder/CMakeLists.txt
patching file misc_modules/rigctl_server/CMakeLists.txt
patching file misc_modules/scanner/CMakeLists.txt
patching file sink_modules/audio_sink/CMakeLists.txt
patching file sink_modules/network_sink/CMakeLists.txt
patching file sink_modules/new_portaudio_sink/CMakeLists.txt
patching file sink_modules/portaudio_sink/CMakeLists.txt
patching file source_modules/airspy_source/CMakeLists.txt
patching file source_modules/airspyhf_source/CMakeLists.txt
patching file source_modules/bladerf_source/CMakeLists.txt
patching file source_modules/file_source/CMakeLists.txt
patching file source_modules/hackrf_source/CMakeLists.txt
patching file source_modules/limesdr_source/CMakeLists.txt
patching file source_modules/plutosdr_source/CMakeLists.txt
patching file source_modules/rtl_sdr_source/CMakeLists.txt
patching file source_modules/rtl_tcp_source/CMakeLists.txt
patching file source_modules/sddc_source/CMakeLists.txt
patching file source_modules/sdrplay_source/CMakeLists.txt
patching file source_modules/soapy_source/CMakeLists.txt
patching file source_modules/spyserver_source/CMakeLists.txt
patching file core/libcorrect/CMakeLists.txt
patch unexpectedly ends in middle of line
Hunk #2 succeeded at 97 with fuzz 2.                                                                                                                                                    [ ok ]
 * Hardcoded definition(s) removed in CMakeLists.txt:
 *      set(CMAKE_INSTALL_PREFIX "/usr/local")
 *      set(CMAKE_INSTALL_PREFIX "/usr")
 * Hardcoded definition(s) removed in source_modules/sddc_source/src/libsddc/CMakeLists.txt:
 *      set(CMAKE_BUILD_TYPE "Release")
>>> Source prepared.
```

Any ideas/updates?

**Comment by drsn0w** [comment]
Thanks for this! I’ll try to take a look at it this weekend and see what’s
going on

**Comment by chron0** [comment]
@drsn0w great, thx! No stress either, for now I just threw a temporary link from lib64 into lib and that seems to work (so the build bin/plugins are actually actually working) - just wanted to leave a note about it.

**Comment by Brumi-2021** [comment]
Hi , @drsn0w thanks a lot for creating those sdrpp ebuilds. !!! 

Let me share here for the rest of pentoo community , several comments about those  sdrpp ebuilds  , 

(1) Regarding the sdrpp-1.0.4.ebuild ,  I could emerge and make it work with two small changes ,
 
a-) As @chron0  was pointing above in that PR  , after emerging it in a amd 64 machine ,  the sw is expecting to have the module files  in the folder lib , but they are stored in lib64 ,  different location , and can not find any module , (rtl, airspy , hackrf ,....) 
(see attached picture ) 


image
 
In my pentoo case, using AMD Ryzen7 , the modules has been placed in  /lib64 :   /usr/lib64/sdrpp/plugins/,   then with sdrpp-1.0.4.ebuild gentoo package install ,  just modifying the config.json   , lib ->lib64 ,  now  all modules work well , and  the programm created all  the modules.json  in the config , as follows. 
 So now sdrpp-1.0.4.ebuild works perfect !!!!!  (I already feedback about it into its sdrpp discord) 

So if you change that line (148) manually in the config.json file  (lib-->lib64) ,  the sw will run perfectly  .

image


b-)  Another small probmem that I found in the sdrpp-1.0.4 , was the incorrect link to the hackrf use flag,  PR #1496 
(but that was already fixed and merged by @ZeroChaos- ) .  So if you synchronize your pentoo system , is already fixed it .

Regarding  sdrpp-9999.ebuild , now NOT  working at the moment , 
Now waiting to be updated  the  sdrpp-9999.ebuild  (but it is NOT urgent , as long as we have sdrpp-1.0.4 working ) .
Other much simple solution , would be that the upstream owner , create a new 1.0,5 stable tag.  (already requested 
by @ZeroChaos-  to  upstream  .) Let's see ... 

Cheers,

**Pull request merged**
