### PR TITLE
net-wireless/qflipper: fix in-app version

### PR DESCRIPTION
**Pull request by thican**
Also:
- cleans-up old files from previously removed ebuilds;
- address QA warnings (based on `pkgcheck scan`) for stable and live ebuilds, ExcessiveLineLength and MultipleKeywordsLine.

Signed-off-by: Thibaud CANALE <thican@thican.net>

### CODE REVIEW

**Comment by thican** [comment]
A note about the `files/qflipper-1.2.2_display_version.patch` patch, we should definitively find a way to upstream this modification thanks to Github workflow when upstream creates a new releases which automatically creates a new archive.

**Comment by blshkv** [comment]
you forgot to sync before creating this pull request. Please review
0fe994fc66b1ff8b0677ac19ccba600b2b66d6f7

and create a new pull if anything else need to be fixed

**Comment by thican** [comment]
What are you talking about? Why did you close this PR?
image

Reopen it, you are wrong I didn’t forget to fetch commit 0fe994fc66b1ff8b0677ac19ccba600b2b66d6f7 as we can see.

I see you add meanwhile other commits on master, I will rebase once you reopen the PR.

**Comment by blshkv** [comment]
hm.... sorry, I can't reopen for some reason. @ZeroChaos- can you help to reopen this request?
image

**Comment by blshkv** [comment]
ok, merged manually. Thanks

**Pull request closed without merging**
