### PR TITLE
pentoo-updater: bashism fix

### PR DESCRIPTION
**Pull request by Scall**

### CODE REVIEW

**Comment by blshkv** [comment]
sorry, what's wrong with the current code?

**Comment by blshkv** [comment]
It is sequence vs grouping. All gentoo ebuilds use {}, see python_compat variable.

Rejected until you provide a good explanation

**Comment by Scall** [comment]
"{3,4,5}" is a bashism, therefore it won't work as expected when /bin/sh is a symlink to a POSIX-compliant shell that is not bash. You can use it in ebuilds because they are bash scripts, but you shouldn't use it in scripts with the #!/bin/sh shebang (instead of #!/bin/bash). It won't work with dash, etc.

**Comment by ZeroChaos-** [comment]
I'm running out the door but I'll test this then merge today

**Comment by ZeroChaos-** [comment]
fixing a few other shellcheck warnings while I tested this, so I'm committing my version which includes your fix.  thanks!

**Comment by blshkv** [comment]
I think an another option is to change shebang to /bin/bash.

**Pull request closed without merging**
